name: Release and deploy Todo

on:
  push:
    branches:
    - 'v[0-9]+.[0-9]'

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Node Action
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Installation
      run: npm i -g @railway/cli
    - name: rw up
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RW_SECRET }}
    - name: Send custom JSON
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nNang Shri Kham Merng"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Metriculation:\nA0265056A"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\ne1045731@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/CherylMerng/GoLangApp"
                  }
                ]
              },
              {
                 "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://punchy-detail-production.up.railway.app"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://punchy-detail-production.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LINK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
