# Name of this workflow
name: Release and deploy Todo

#1 Triggering pipeline with a branch name format - This workflow will run whenever the repo receives a push
on:
  push:
    branches:
    - 'v[0-9]+.[0-9]' 

# Jobs to perform in the workflow
jobs:
  release-and-deploy:
    # OS that this job will be running on
    runs-on: ubuntu-latest  #key: value
    #5 The pipeline should not run if the commit message starts with #NORUN
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    # list of steps to perform task
    steps:
    - name: Echo the branch name
      run: echo "current branch - ${{ github.ref_name }}"
    - name: Checkout the branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    - name: Node Action
      uses: actions/setup-node@v3
      with:
        node-version: 16
    #2 Railway installation | Using Github Actions with Railway
    - name: Install
      run: npm i -g @railway/cli
    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RW_SECRET }}
    #3 Create a release using the branch name
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }} #node name
      with:
        tag_name: ${{ github.run_number }}
        release_name: ${{ github.ref_name }}
    #4 Send a noti to Slack | Creating interactive messages + Slack Send GitHub Action
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: | #"key": "value"
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Name:\nNang Shri Kham Merng"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Matriculation:\nA0265056A"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Email:\ne1045731@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "Repository:\nhttps://github.com/CherylMerng/GoLangApp"
                  }
                ]
              },
              {
                 "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "Deployment:\nhttps://golang-app.up.railway.app/"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://golang-app.up.railway.app/|Open Application>"
                }
              }
            ]
          }
  
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_LINK }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK